build: false

skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: '12.15.0'

configuration: Release
platform:
  - x86
  - x64

install:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - ps: If ($env:nodejs_version -eq "12.15.0") { npm run prebuild }

artifacts:
  - path: prebuilds
    name: $(APPVEYOR_REPO_TAG_NAME)-win-$(PLATFORM)
    type: zip

deploy:
  - provider: GitHub
    artifact: /.*\.zip/
    draft: false
    prerelease: true
    auth_token:
      secure: 'LB3VfTC/Oq0+VmnRuGpwpG4Gj3FJKpd8ch3KyPha0BTkDJ6xvBu7WOEb72uoPd6hat9hwTi/cOAc8gODkbmlRB0+DeQeTEVGXWj+aJCnq4m7CAQ9E1Cwlqf1XfYGF/xT0ZuHO6e3yoIxpH8efWlDRnbZFfRI/NTBit9ySx3Df6OghFi9ez2VQjd9sMMSchBjcmuVk9L85dx3rxd38KBXYZnZIDfpao290MSqeBT6tcxz5L4XFYBPWgd9x1nULxmJpbdYwqyjLVESwZs1M4q0+cIUzBPkuHKhmN0+1vZFeK4HLBBLH4238S7bxYkwxRxhmYJLZBsWBz6vZfrPV36+THqjsr/t0yuCMb6aa2Qhnboy9A9GaOcNeLz7n7g55+b7arWr0oUeyqMFDcJrAKn+QgALyrjcruq6xmwEEakITCGwmTs+luAgu76pEBilVjq0htaJlhzVVrXIFXyrcMrm12ZtszuoktsghUW62UmPSEwMvqT2xMsWGRQjWZGxzVNUrYHZ4hi9L3evEjr/LtBD2l6uyZpOJaKtJ6/+Svw+z98LPYyQPOHBxscuc+QrtJjVqaQkh9gBPsVMbCLGgyYPhQJMZqENFhkOHZ8TMK7QZDEcCpGFGPoJBkqiW5domr8G6Q372kBZ/R7XAAZU+OoKfXkdN1ASEYiNqsGesHkxVlk='
    on:
      appveyor_repo_tag: true
      nodejs_version: '12.15.0'
